### ISSUE TITLE
Нерабочие дни с сохранением заработной платы

### ISSUE THREAD

**Issue by DimNS** [d10xa/holidays-calendar#13]
Ковид внёс такое понятие как "Нерабочие дни с сохранением заработной платы" у Консультант+ они помечаются в таблице звездочками сносок на текст указа, предлагаю такие дни вынести в отдельный элемент json "nowork_with_salary"

Кейс: я использую календарь для расчета ЗП (в формуле учитывается количество рабочих дней, вместе с этими днями с сохранением ЗП), а также в проекте используется календарь для расчета сроков выполнения работ и там учитываются только рабочие дни (выходные с сохранением ЗП не входят в их число), и вот мне надо для разных случаев знать какие дни выходные, но для расчета ЗП считаются рабочими

**Comment by d10xa** [comment]
Нерабочие дни с сохранением заработной платы я назвал `nowork`. 

```json
{
"nowork": [
        "2021-05-04",
        "2021-05-05",
        "2021-05-06",
        "2021-05-07",
        "2021-11-01",
        "2021-11-02",
        "2021-11-03"
    ]
}
```

**Comment by DimNS** [comment]
Оооо, я не заметил, прошу прощения за тикет
