### ISSUE TITLE
Работает ли CRON c consultant?

### ISSUE THREAD

**Issue by pohodnya** [d10xa/holidays-calendar#14]
Добрый день. Заметил что [ссылка в документации на CRON build](https://travis-ci.com/d10xa/holidays-calendar/builds) отдает 404. Насколько актуальные сейчас календари и продолжается ли поддерживаться данный репозиторий?

**Comment by d10xa** [comment]
CI перестал работать, надо будет разобраться в чём дело. Календари актуальные до 2022. На следующий год добавлю в этом месяце

**Comment by d10xa** [comment]
Заменил travis-ci на github actions
https://github.com/d10xa/holidays-calendar/actions/runs/3257778333
