### ISSUE TITLE
2024

### ISSUE THREAD

**Issue by Fxlr8** [d10xa/holidays-calendar#15]
На консультанте появился производственный календарь на 2024. Когда будут свежие данные? Или мб нужна помощь с этим?

**Comment by d10xa** [comment]
<img width="551" alt="image" src="https://github.com/d10xa/holidays-calendar/assets/10722234/9910fb74-a53b-4e89-b66b-8c1cf1a4e620">

Консультант отличается от superjob в некоторых днях. Пока не буду обновлять

**Comment by tesselogy** [comment]
Привет, спасибо за информацию. Обновлю в течении дня

чт, 24 авг. 2023 г. в 21:14, Andrey Stolyarov ***@***.***>:
