### ISSUE TITLE
Unsupported class file major version N

### ISSUE THREAD

**Issue by Argimko** [d10xa/holidays-calendar#16]
Привет! Подскажи, плиз, как исправить ошибку компиляции парсера. Вроде бы по матрице совместимости всё верно: https://docs.gradle.org/current/userguide/compatibility.html

![image](https://github.com/d10xa/holidays-calendar/assets/3511036/fc2528dc-c9ee-4656-915c-d8cb4d792582)

Спасибо!

**Comment by d10xa** [comment]
работает на java 11, на других не проверял

**Comment by Argimko** [comment]
Спасибо! Отпишусь, когда проверю
