### ISSUE TITLE
Производственный на 2021 год

### ISSUE THREAD

**Issue by popcorn2d** [d10xa/holidays-calendar#6]
Сабж в шапке, будет json на 2021 год?)

**Comment by popcorn2d** [comment]
Из консультанта

**Comment by d10xa** [comment]
Сейчас календарь на 2021й год опубликован на сайте консультанта в статусе "проект". Добавлю, когда утвердят

**Comment by popcorn2d** [comment]
Спасибо)

**Comment by d10xa** [comment]
2021 добавлен
